compiler:
    evm_version: istanbul
    solc:
        version: 0.5.17
        optimizer:
            enabled: true
            runs: 200
        remappings:
            - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@2.5.0"

console:
    show_colors: true
    color_style: monokai
    auto_suggest: true
    completions: true

autofetch_sources: false
dependencies:
    - OpenZeppelin/openzeppelin-contracts@2.5.0
